config/routes.rb
Txi::Application.routes.draw do
  resources :menus
  root :to => "menus#new"
end

app/models/menu.rb
require 'csv'

class FileValidator < ActiveModel::Validator
  def validate(menu)
    if !menu.file
      menu.errors[:base] << "No file has been uploaded!"
    elsif !menu.parse_file
      menu.errors[:base] << "There was a problem reading the uploaded file. Make sure it's formatted correctly."
    end
  end
end


class Menu < ActiveRecord::Base
  attr_accessible :items, :total, :file

  validates_with FileValidator

  serialize :items, Hash

  def parse_file

    self.file = IO.read(self.file.path)

    begin
      array = CSV.parse(self.file)
    rescue CSV::MalformedCSVError => e
      return false
    end
    # The first element is the total price we're trying to reach
    # Don't forget to remove the dollar sign
    total = array.shift.first.split('$').last.to_f
    # Convert to pennies, otherwise math gets messed up
    total *= 100;
    # Convert the nested arrays into a Hash for easier organization
    hash = {}
    array.each do |a|
      # Remove the dollar sign from the amounts
      a[1] = a[1].split('$').last.to_f
      # Convert to pennies
      a[1] = (a[1] * 100).to_i
      hash[a[0]] = a[1]
    end
    self.total = total
    self.items = hash
  end

  def get_working_combination
    # First eliminate any items that are already more than the total
    items.delete_if {|item, price| price > total}
    # Find how many of the cheapeast items you can add while <= total. This is the largest possible number of items
    cheapest = items.values.sort!.first
    max_item_count = (total / cheapest).floor
    i = 1
    until i > max_item_count
      # The array combination method will give us every possible combination of i members of a set
      # But each number is unique, so we need to add alternate versions of each number
      # in order to allow for multiple orders of the same item.
      possible_items = []
      items.values.each do |val|
        pushcount = 0
        i.times do
          # Make sure that the copies of this item don't exceed the total
          pushcount += 1
          if (pushcount * val) <= total
            possible_items.push(val)
          end
        end
      end
      tests = possible_items.combination(i).to_a
      tests.each do |test|
        sum = test.inject{|sum, x| sum + x}
        # For debugging
        #puts "#{test} sum: #{sum}"
        return test if sum == total
      end
      i += 1
    end
    return false
  end

  def solve_for_total
    # Figure out which, if any, combination of items can add up to the total
    # This slows down a lot for larger menus or amounts than the sample. Could stand to be optimized
    if combo = get_working_combination
      # Match the combo's prices to the menu items before returning solution
      solution = []
      combo.each do |food|
        # If multiple items have the same price, just return the first item with that price, since we only need one solution
         solution.push(items.select{|key, val| val == food}.keys.first)
      end
      solution
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    redirect_to [:new, :menu]
  end

  def show
    @menu = Menu.find(params[:id])
    @solution = @menu.solve_for_total
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, {"notice" => "We have processed your menu problem!"}}
      else
        @errors = @menu.errors[:base]
        format.html { render action: "new"}
      end
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_cents_as_dollars(price)
    number_to_currency(price/100.0)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Menu Solver Pro
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .content
      .row
        .span6.offset6#mainbox
          .header
            %h1 Menu Solver
            %h2 Pro
            %h3 2000-EX
          = yield

app/views/menus/_form.html.haml
- if @errors
  %span.error
    - @errors.each do |e|
      %p
        = e
    %p Please try again.
= simple_form_for @menu, :html => {:multipart => true} do |f|
  = f.file_field :file, :required => true
  = f.button :submit, :value => "Show me the solution!"

app/views/menus/create.html.haml
= @items

app/views/menus/new.html.haml
%p Welcome to Menu Solver Pro! We provide Menu solutions.
%p To use Menu Solver Pro, you will need your menu in a text file. Your text file should look like this:
%ul.format
  %li $[The total amount you would like to spend]
  %li [Name of menu item 1],$[Price of menu item 1]
  %li [Name of menu item 2],$[Price of menu item 2]
  %li ...and so on until the end of the menu
%p Here's a sample menu:
%ul.format.sample
  %li $15.05
  %li mixed fruit,$2.15
  %li french fries,$2.75
  %li side salad,$3.35
  %li hot wings,$3.55
  %li mozzarella sticks,$4.20
  %li sampler plate,$5.80

Upload your menu below and we will show you a sample order that will add up to your desired total (if it's possible).
= render 'form'

app/views/menus/show.html.haml
%p#notice= notice

%h4 Desired total
.total
  = format_cents_as_dollars(@menu.total)
%h4 Items
%ul.menu
  - @menu.items.each do |item, price|
    %li
      %span.column
        = item
      %span.column
        = format_cents_as_dollars(price)
%h4 Solution
- if @solution
  %ul.solution
    - @solution.each do |item|
      %li
        %span.column
          = item
        %span.column
          = format_cents_as_dollars(@menu.items[item])
    %li
      %hr
      %li
      %span.column
        %h5 Total
      %span.column
        %strong
          = format_cents_as_dollars(@menu.total)

- else
  Sorry, there's no way to get that total with these items.
.retry
  .btn
    = link_to 'Try another menu', new_menu_path